theme: jekyll-theme-midnight
title: Portico Exchange
description: DEX on Lightning Network
baseurl: ""
url: "https://proticoexchange.github.io"
logo: https://user-images.githubusercontent.com/83122757/160579966-360666b0-3830-490b-b30c-e4c8c5752872.png
